name: My CI

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

# this is a comment 

jobs:
  hello:
    name: My first job
    runs-on: ubuntu-latest
    steps:
      - name: My first step
        run: echo "Hello world"
      - name: Step with output
        id: step2
        run: echo "my_var=some-value" >> $GITHUB_OUTPUT

  test:
    name: Run tests
    strategy:
      matrix:
        os: ['ubuntu-latest', 'windows-latest']
        python-version: ['3.9','3.13']
        include: 
          - os: 'macos-latest'
            python-version: '3.11'
    runs-on: ${{ matrix.os }}
    steps:
      - name: Check out repo
        uses: actions/checkout@v4
        with:
          python-version: ${{ matrix.python-version }}
      - run: echo "Running in ${{ matrix.os }}  with python version ${{ matrix.python-version }}."
      - name: Only runs on Linux
        if: matrix.os == 'ubuntu-latest'
        run: echo "This is linux"
      - name: Install package
        run: pip install .[test]
      - name: Run Pytest
        run: python -m pytest -v



## some jobs pass information to each other

new-job:
  needs: [hello]
  runs-on: ubuntu-latest
  steps:
    - name: Print output from first job
      run: echo "#{{ needs.hello.outputs.my_var }}"